### ISSUE TITLE
Update to support .NET 4.5

### ISSUE THREAD

**Issue by niemyjski** [einaregilsson/InsertIcons#5]
Is there any chance you could just update the target framework to 4.5 and recompile/release. We use this and on windows 10 machines it's asking us to download and install .net 3.5

**Comment by einaregilsson** [comment]
I don't want to release without testing, and I don't have Windows 10 to test on right now, or the time to do it. So you're probably better off just getting the source code and compiling a new version yourself, since I don't know when I can get to this.

Also, it sounds strange that it's asking you to download .NET 3.5, I thought newer .net version should always be able to run older assemblies?

**Comment by niemyjski** [comment]
As long as it's tested on 4.5 it will work, I just get the prompt saying 3.5 is not installed click here to install

**Comment by ntegrl** [comment]
To any who see this,

I have created a fork of InsertIcons which has a simple to use GUI that runs on the latest .NET Framework (4.6.1 as of the time this was written) and is available here: https://github.com/ntegrl/XInject

Hopefully this will help out anyone in need of injecting icons into their assemblies and I also wish to thank Einar for his original contribution.

**Comment by niemyjski** [comment]
@einaregilsson any chance we can get an updated official release? I'm going to recompile it myself for now.

**Comment by einaregilsson** [comment]
@niemyjski Still don't have a Windows machine, although I have a virtual machine somewhere. I'll try to get to it in the next couple of weeks, but no promises.
